[tool.poetry.dependencies]
ansible = "10.4"
ansible-lint = { version = "^24.2.3", markers = "platform_system != 'Windows'" }

[tool.poetry]
version = "1.0.0"
description = "Python macro deploy."
authors = ["Michael Amadi <amadimicheal212@gmail.com>"]
readme = "README.md"
package-mode = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"




export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

eval "$(pyenv virtualenv-init -)"