name: 'Get_Cache_Dependencies'
description: 'Get the Dependencies and Cache them'
runs:
  using: 'composite'
  steps:
    - name: Load cached venv
      continue-on-error: true
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.install-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}            


