name: 'Get_Cache_Dependencies'
description: 'Get the Dependencies and Cache them'
runs:
  using: 'composite'
  steps:
    - name: Load cached venv
      continue-on-error: true
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.install-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}            
    #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: init poetry env
      if: success() && ${{ steps.install_poetry.outcome == 'success' }}
      # if:failure() & steps.install_poetry.outcome == 'failure' }}
      run: poetry init
      shell: bash
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
          poetry lock --no-update
          poetry install --no-interaction --no-root
          echo "poetry done..."
      shell: bash

