name: 'Get_Cache_Dependencies'
description: 'Get the Dependencies and Cache them'
inputs:
  caching:
    description: 'whether to cache dependencies or not'
    required: true
    default: 'true'
runs:
  using: 'composite'
  steps:
    #----------------------------------------------
    #------  cache Poetry and dependencies  -------
    #----------------------------------------------  
    - name: Check custom action
      shell: bash
      run: |
        echo "Custom Action working..."