name: 'Get_Cache_Dependencies'
description: 'Get the Dependencies and Cache them'
inputs:
  custom_input:
    description: 'custom action input'
    required: true
    default: 'true'
outputs:
  custom_output:
    description: 'custom action output'
    value: ${{ steps.check_custom_action.outputs.custom_input_value }}   
runs:
  using: 'composite'
  steps:
    #----------------------------------------------
    #------  cache Poetry and dependencies  -------
    #----------------------------------------------  
    - name: Check custom action
      id: check_custom_action
      shell: bash
      run: |
        echo "Custom Action working..."
        echo "custom_input_value='${{ inputs.custom_input }}'" >> $GITHUB_OUTPUT