name: Actions for Python Project
on: 
  push:
    branches:
      - 'main'
      - 'dev-*'
      - 'feature/**'
    #branches-ignore:
    paths-ignore:
      - 'state_files/*'
  #pull_request:
    #types: 
      #- opened
      #- closed
      #- reopened
  workflow_dispatch:

env:
  POETRY_VERSION: "1.5.1"
  
jobs: 
  deploy_python_macro:
    strategy:
        matrix:
          python-version: ['3.9','3.10']  # Choose compatible versions
          operating-system: [ubuntu-latest]
          exclude:
            - python-version: 3.8
              operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }}
    outputs:
      script-file: ${{ steps.write_py_file.outputs.py_output_file }}
    steps:
        #----------------------------------------------
        #       check-out repo and set-up python
        #----------------------------------------------
        - name: Get code
          uses: actions/checkout@v3
            #with:
        - name: setup python
          id: install-python
          uses: actions/setup-python@v4
          with: 
            python-version: ${{ matrix.python-version }}
        #----------------------------------------------
        #------  cache Poetry and dependencies  -------
        #----------------------------------------------
        - name: Cache poetry installation
          uses: actions/cache@v4
          with:
            path: ~/.cache/pypoetry
            key: poetry-cache-${{ runner.os }}-${{ steps.install-python.outputs.python-version }}-${{ env.POETRY_VERSION }}
        - name: Cache Packages
          uses: actions/cache@v3
          with:
              path: ~/.local
              key: poetry-local-${{ runner.os }}-${{ steps.install-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}            
        #----------------------------------------------
        #  -----  install & configure poetry  ---------
        #----------------------------------------------
        - name: install poetry
          uses: snok/install-poetry@v1
          id: install_poetry
          with:
            version: ${{ env.POETRY_VERSION }}
            virtualenvs-create: true
            virtualenvs-in-project: true
            #virtualenvs-path: ~/my-custom-path
            installer-parallel: true
        #---------------------------------------------------------
        #   load cached venv if cache exists using custom actions
        #---------------------------------------------------------
        - name: Load & cache dependencies
          uses: ./.github/actions/cached-deps
        #----------------------------------------------
        # install dependencies if cache does not exist
        #----------------------------------------------
        - name: init poetry env
          if: success() && ${{ steps.install_poetry.outcome == 'success' }}
          # if:failure() & steps.install_poetry.outcome == 'failure' }}
          run: poetry init
          shell: bash
        - name: Install dependencies
          if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
          run: |
            poetry env use ${{ matrix.python-version }}
            poetry lock --no-update
            poetry install --no-interaction --no-root
            echo "poetry done..."
          shell: bash          
        - name: run deploy_macro using poetry
          id: write_py_file
          run: |
            source .venv/bin/activate
            poetry completions bash >> ~/.bash_completion
            poetry run python3 deploy_macro.py
            compact_output=$(cat py_output.json | jq -c '.')
            echo "py_output_file=${compact_output}" >> $GITHUB_OUTPUT
            echo "loading workflow secret: ${{ secrets.ACTIONS_WORKFLOW_SECRET }}"
          # poetry build
          #working-directory: "./app"
  deploy_ansible:
    environment: ClickHouse-UAT
    env:
      PLAYBOOK_DIR: ./playbooks/proj_name/
    needs: [deploy_python_macro]
    #container:
      #image:
      #env: 
    #services:
      #ansible_service:
        #image:
        #ports:
        #  - 2489:2489
        #env:
    runs-on: ubuntu-latest
    steps:
      - name: install ansible and ansible-list with specific version.
        run: |
          source .venv/bin/activate
          poetry add ansible==2.14.0 ansible-lint==6.0.0 
          ansible_version=$(ansible --version)
          ansible_lint_version=$(ansible-lint --version)
          echo "installed Ansible version: $ansible_version"  
          echo "installed Ansible Lint version: $ansible_lint_version" 
      - uses: actions/checkout@v4
      #- name: install ansible-lint
        #uses: ansible/ansible-lint@v6
        # optional (see below):
        #with:
          #args: "-f full --fix=none --force-colour"
          #setup_python: "true"
          #working_directory: ""
          #requirements_file: ""      
      - name: Output generated py file and playbook directory
        run: |
          echo "${{ needs.deploy_python_macro.outputs.script-file }}"
          echo "playbook directory set to: ${{ env.PLAYBOOK_DIR }}"
          echo "loading environment secret: ${{ secrets.CH_UAT_USER_PASSWD }}"
  display_deployment_base_info:
    needs: [deploy_python_macro, deploy_ansible]
    if: always()
    uses: ./.github/workflows/output.yml   ## reusable workflow
    with:
      artifact-name: "${{ needs.deploy_python_macro.outputs.script-file }}"
    #secrets:
      #reusable-secret: 
  display_deployment_outcome:
    needs: display_deployment_base_info
    runs-on: ubuntu-latest
    steps:
      - name: Check output of dpeloyment
        run: echo "${{ needs.display_deployment_base_info.outputs.deployment-results }}"
        
## end of workflow.        